Fix build issue with ML-DSA 44 only. Fix --enable-mlkem=all to enable features (keygen/enc/dec) to match --enable-dilithium behavior and allow uses like: `--enable-mlkem=all,512,small`. Fix issue building mem track with missing `PRINT_HEAP_ADDRESS` (reproduced with `--enable-trackmemory=verbose --enable-stacksize=verbose`).
```
wolfcrypt/src/dilithium.c:6696:21: error: expected expression before '}' token
 6696 |                     }
      |
```